### ISSUE TITLE
[Border] Vereine config.yml Optionen

### ISSUE THREAD

**Issue by AlexanderRitter02** [AlexanderRitter02/varo-issues#17]
**Der Vorschlag**
Da die Border so viele Einstellungen hat, vereine diese als Suboptionen in der `config.yml`.
```
border:
  mode: EDGE
  shrink-time: 672
  radius: 5000
  end-radius: 250
```
